#!/usr/bin/env sh
exec poke -L "$0" "$@"
!#
load argp;
load gpt;
load hfs;

var args = argv'length < 1 ? ["--help"] : argv;

argp_parse :program "hfs-describe"
           :summary "displays some info about HFS filesystems"
           :argv args
           :allow_unknown 1;

var file = open(argv[0], IOS_M_RDONLY);
var gpt = GPT @ file : 0#B;

for (part in gpt.partitions where part.pt_guid.guid == GPT_PT_HFS_PLUS) {
    var vol = HFSPlusVolume @ file : gpt.partitions[0].first_lba;
    printf("%Tv\n", vol);
    break;
}

close(file);
